import sys
sys.path.append('./')
import tools.extractSaveData as extractSaveData
import tools.dataAnalysis as dataAnalysis
import tools.createPublicationVisualizations as createPublicationVisualizations
import tools.parameters as par
import numpy as np
import matplotlib.pyplot as plt
import pdb
import pickle


figVersion = '0.1'
mouse ='220211_f38'#,'220214_f43','220205_f57','220205_f61','220507_m81','220507_m90','220525_m19','220525_m27','220525_m28']
expDate = 'all'  #  'some', 'all', 'allMLI' or 'allPC'
recordings = 'all' # 'some', 'all', 'allMLI' or 'allPC'
experiment='ephy'
groupAnalysisDir = '/media/HDnyc_data/data_analysis/in_vivo_cerebellum_walking/LocoRungsData/simplexSummary'
pickleFileName2 = groupAnalysisDir + f'/behavior_data_{experiment}'
pickleFileName1 = groupAnalysisDir + f'/behavior_data_trajectories_{experiment}'
stridePar=pickle.load( open( pickleFileName2, 'rb' ) )
strideTraj=pickle.load( open( pickleFileName1, 'rb' ) )
eSD         = extractSaveData.extractSaveData(mouse,recStruc='simplexEphy')
(foldersRecordings,dataFolders,listOfRecordings) = eSD.getEphysRecordingsList(expDate=expDate,recordings=recordings) # get recordings for specific mouse and date
#pdb.set_trace()
cPV = createPublicationVisualizations.createVisualizations(eSD.publicationFigLocation,mouse)
#the variables to be plotted, the pickle files were generated by the corresponding scrip
#each parameter is saved in an array with structure: [daily average of paw and trial mean, daily average containing all trials, some statistics, daily average of trial for individual paws]
#in each array: row is an animal, column contains animal name in indice 0, and values across day in indice 1

swingNumber = pickle.load(open(groupAnalysisDir + '/%s_swingNumber.p'%experiment, 'rb'))
strideDuration = pickle.load(open(groupAnalysisDir + '/%s_strideDuration.p'%experiment, 'rb'))
swingSpeed = pickle.load(open(groupAnalysisDir + '/%s_swingSpeed.p'%experiment, 'rb'))
rungCrossed = pickle.load(open(groupAnalysisDir + '/%s_runCrossed.p'%experiment, 'rb'))
indecisiveStrideFraction = pickle.load(open(groupAnalysisDir + '/%s_indecisiveSwings.p'%experiment, 'rb'))
pawCoordination=pickle.load(open(groupAnalysisDir + '/%s_pawCoordination.p'%experiment,'rb'))
allVariablesDf = pickle.load(open(groupAnalysisDir + '/%s_allBehaviorParam.p'%experiment,'rb'))
strideLength = pickle.load(open(groupAnalysisDir + '/%s_strideLength.p' % experiment, 'rb'))

# cPV.fig_locomotorLearning(figVersion, stridePar, strideTraj,swingNumber,strideLength,strideDuration,indecisiveStrideFraction,swingSpeed,pawCoordination,allVariablesDf)
# cPV.fig_locomotorLearningSupp(figVersion, stridePar, strideTraj,swingNumber,strideLength,strideDuration,indecisiveStrideFraction,swingSpeed,pawCoordination,allVariablesDf)
cPV.fig_locomotorLearning_supp_FR(figVersion, stridePar, strideTraj)