#!/usr/bin/env python3
"""
zenodo_package.py  --  auto-generated by packageZenodoData.py
Converts video_000.ma -> video_000.avi (MJPG) and packages data
into one tar.gz per animal for Zenodo upload.

Requirements: h5py, opencv-python, numpy
Usage:
  python zenodo_package.py [--dest /path/to/output] [--quality 85] [--animal 220211_f38]
"""

import h5py
import cv2
import numpy as np
import os
import shutil
import tarfile
import argparse
import sys
from datetime import datetime

BASE_DATA    = '/media/invivodata2/altair_data/dataMichael'
DEFAULT_DEST = '/media/HDnyc_data/data_analysis/in_vivo_cerebellum_walking/LocoRungsData/packagedData'
VIDEO_FILE   = 'video_000.ma'
VIDEO_OUT    = 'video_000.avi'

MANIFEST = {
    '220211_f38': [
        ('2022.04.26_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.04.26_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.04.26_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.26_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.04.27_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.04.27_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.04.27_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.04.27_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.28_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.04.28_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.04.28_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.28_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.04.28_000', 'locomotionEphys2Motor60sec_005'),
        ('2022.04.29_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.29_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.04.29_000', 'locomotionEphys2Motor60sec_005'),
        ('2022.04.29_000', 'locomotionEphys2Motor60sec_006'),
        ('2022.05.02_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.02_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.02_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.02_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.02_000', 'locomotionEphys2Motor60sec_005'),
        ('2022.05.02_000', 'locomotionEphys2Motor60sec_006'),
        ('2022.05.02_000', 'locomotionEphys2Motor60sec_007'),
        ('2022.05.02_000', 'locomotionEphys2Motor60sec_008'),
        ('2022.05.03_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.03_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.03_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.03_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.03_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.04_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.04_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.04_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.04_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.04_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.05_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.05_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.05_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.05_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.05_000', 'locomotionEphys2Motor60sec_004'),
    ],
    '220214_f43': [
        ('2022.04.26_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.04.26_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.27_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.04.27_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.04.27_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.04.28_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.04.28_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.04.28_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.28_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.04.28_001', 'locomotionEphys2Motor60sec_005'),
        ('2022.04.29_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.04.29_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.04.29_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.04.29_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.02_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.02_003', 'locomotionEphys2Motor60sec_005'),
        ('2022.05.02_003', 'locomotionEphys2Motor60sec_006'),
        ('2022.05.03_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.03_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.03_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.05_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.05_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.05_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.05_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.05_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.06_001', 'locomotionEphys2Motor60sec_004'),
    ],
    '220205_f57': [
        ('2022.04.28_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.04.28_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.04.28_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.04.28_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.28_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.02_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.02_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.02_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.02_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.02_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.03_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.03_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.03_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.03_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.03_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.04_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.04_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.04_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.04_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.04_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.05_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.05_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.05_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.05_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.05_002', 'locomotionEphys2Motor60sec_005'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_005'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_006'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_007'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_008'),
        ('2022.05.06_002', 'locomotionEphys2Motor60sec_009'),
    ],
    '220205_f61': [
        ('2022.04.26_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.04.26_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.26_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.04.26_003', 'locomotionEphys2Motor60sec_005'),
        ('2022.04.26_003', 'locomotionEphys2Motor60sec_006'),
        ('2022.04.26_003', 'locomotionEphys2Motor60sec_007'),
        ('2022.04.26_003', 'locomotionEphys2Motor60sec_008'),
        ('2022.04.28_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.04.28_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.04.28_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.04.28_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.04.28_003', 'locomotionEphys2Motor60sec_005'),
        ('2022.04.28_003', 'locomotionEphys2Motor60sec_006'),
        ('2022.05.02_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.02_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.02_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.02_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.02_002', 'locomotionEphys2Motor60sec_005'),
        ('2022.05.02_002', 'locomotionEphys2Motor60sec_006'),
        ('2022.05.03_003', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.03_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.03_003', 'locomotionEphys2Motor60sec_006'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_005'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_006'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_007'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_008'),
        ('2022.05.04_003', 'locomotionEphys2Motor60sec_009'),
        ('2022.05.05_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.05_003', 'locomotionEphys2Motor60sec_001'),
        ('2022.05.05_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.05_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.05_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.05_003', 'locomotionEphys2Motor60sec_005'),
        ('2022.05.06_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.05.06_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.05.06_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.05.06_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.05.06_003', 'locomotionEphys2Motor60sec_005'),
        ('2022.05.06_003', 'locomotionEphys2Motor60sec_006'),
    ],
    '220507_m81': [
        ('2022.07.20_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.20_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.20_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.20_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_005'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_006'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_007'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_008'),
        ('2022.07.21_000', 'locomotionEphys2Motor60sec_009'),
        ('2022.07.22_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.22_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.22_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.22_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.22_000', 'locomotionEphys2Motor60sec_005'),
        ('2022.07.22_000', 'locomotionEphys2Motor60sec_006'),
        ('2022.07.22_000', 'locomotionEphys2Motor60sec_007'),
        ('2022.07.25_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.25_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.26_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.26_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.26_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.26_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.26_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.27_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.27_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.27_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.27_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.28_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.28_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.28_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.28_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.28_000', 'locomotionEphys2Motor60sec_005'),
        ('2022.07.28_000', 'locomotionEphys2Motor60sec_006'),
        ('2022.07.29_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.29_000', 'locomotionEphys2Motor60sec_002'),
    ],
    '220507_m90': [
        ('2022.07.20_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.20_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.20_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.20_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.20_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_005'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_006'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_007'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_008'),
        ('2022.07.21_001', 'locomotionEphys2Motor60sec_009'),
        ('2022.07.22_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.22_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.22_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.22_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.22_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.25_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.25_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.25_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.25_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.25_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.26_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.26_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.26_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.26_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.26_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_005'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_006'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_007'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_008'),
        ('2022.07.27_001', 'locomotionEphys2Motor60sec_009'),
        ('2022.07.28_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.28_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.28_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.28_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.28_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.29_001', 'locomotionEphys2Motor60sec_000'),
    ],
    '220525_m19': [
        ('2022.07.25_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.25_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.25_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.25_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.25_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.26_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.26_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.26_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.26_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.26_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.27_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.27_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.27_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.27_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.27_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.29_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.29_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.29_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.29_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.29_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.01_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.01_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.01_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.01_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.01_000', 'locomotionEphys2Motor60sec_005'),
        ('2022.08.01_000', 'locomotionEphys2Motor60sec_006'),
        ('2022.08.02_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.02_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.03_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.03_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.03_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.03_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.03_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.04_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.04_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.04_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.04_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.04_000', 'locomotionEphys2Motor60sec_004'),
    ],
    '220525_m27': [
        ('2022.07.25_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.25_003', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.25_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.25_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.25_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.26_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.26_003', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.26_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.26_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.26_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.27_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.27_003', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.27_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.27_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.27_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.28_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.28_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.28_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.28_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.28_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.29_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.29_003', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.29_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.29_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.29_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.01_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.01_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.01_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.01_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.01_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.02_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.02_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.02_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.02_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.02_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.03_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.03_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.03_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.03_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.03_001', 'locomotionEphys2Motor60sec_005'),
        ('2022.08.03_001', 'locomotionEphys2Motor60sec_006'),
        ('2022.08.03_001', 'locomotionEphys2Motor60sec_007'),
        ('2022.08.04_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.04_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.04_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.04_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.04_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.05_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.05_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.05_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.05_000', 'locomotionEphys2Motor60sec_004'),
    ],
    '220525_m28': [
        ('2022.07.25_004', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.25_004', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.25_004', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.25_004', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.25_004', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.25_004', 'locomotionEphys2Motor60sec_005'),
        ('2022.07.25_004', 'locomotionEphys2Motor60sec_006'),
        ('2022.07.26_004', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.26_004', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.26_004', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.26_004', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.27_004', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.27_004', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.27_004', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.27_004', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.27_004', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.27_004', 'locomotionEphys2Motor60sec_005'),
        ('2022.07.28_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.28_003', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.28_003', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.28_003', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.28_003', 'locomotionEphys2Motor60sec_004'),
        ('2022.07.29_004', 'locomotionEphys2Motor60sec_000'),
        ('2022.07.29_004', 'locomotionEphys2Motor60sec_001'),
        ('2022.07.29_004', 'locomotionEphys2Motor60sec_002'),
        ('2022.07.29_004', 'locomotionEphys2Motor60sec_003'),
        ('2022.07.29_004', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.01_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.01_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.01_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.01_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.01_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.01_002', 'locomotionEphys2Motor60sec_005'),
        ('2022.08.02_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.02_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.02_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.02_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.02_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.03_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.03_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.03_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.03_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.03_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.04_002', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.04_002', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.04_002', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.04_002', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.04_002', 'locomotionEphys2Motor60sec_004'),
        ('2022.08.05_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.08.05_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.08.05_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.08.05_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.08.05_001', 'locomotionEphys2Motor60sec_004'),
    ],
    '220716_f65': [
        ('2022.09.15_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.15_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.15_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.09.15_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.09.15_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.09.19_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.19_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.19_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.09.19_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.09.19_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.09.21_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.21_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.21_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.09.21_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.09.22_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.22_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.22_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.09.22_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.09.22_000', 'locomotionEphys2Motor60sec_004'),
        ('2022.09.23_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.23_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.23_000', 'locomotionEphys2Motor60sec_002'),
    ],
    '220716_f67': [
        ('2022.09.13_003', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.13_003', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.15_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.15_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.15_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.09.15_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.09.15_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.09.19_001', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.19_001', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.19_001', 'locomotionEphys2Motor60sec_002'),
        ('2022.09.19_001', 'locomotionEphys2Motor60sec_003'),
        ('2022.09.19_001', 'locomotionEphys2Motor60sec_004'),
        ('2022.09.27_000', 'locomotionEphys2Motor60sec_000'),
        ('2022.09.27_000', 'locomotionEphys2Motor60sec_001'),
        ('2022.09.27_000', 'locomotionEphys2Motor60sec_002'),
        ('2022.09.27_000', 'locomotionEphys2Motor60sec_003'),
        ('2022.09.27_000', 'locomotionEphys2Motor60sec_004'),
    ],
}


def log(msg):
    print(f'[{datetime.now().strftime("%H:%M:%S")}] {msg}', flush=True)


def convert_video(src_ma, dst_avi, quality):
    """Convert an ACQ4 video .ma (HDF5) to MJPG .avi frame-by-frame."""
    with h5py.File(src_ma, 'r') as f:
        frames = f['data']
        times  = f['info/0/values'][()]
        n      = frames.shape[0]
        h, w   = frames.shape[1], frames.shape[2]
        is_color = (frames.ndim == 4)
        fps    = n / (times[-1] - times[0]) if times[-1] > times[0] else 25.0

        fourcc = cv2.VideoWriter_fourcc('M', 'J', 'P', 'G')
        writer = cv2.VideoWriter(dst_avi, fourcc, fps, (w, h))
        try:
            writer.set(cv2.VIDEOWRITER_PROP_QUALITY, quality)
        except AttributeError:
            pass  # older OpenCV versions

        for i in range(n):
            frame = frames[i]
            if frame.dtype != np.uint8:
                frame = (frame >> 8).astype(np.uint8)
            if not is_color:
                frame = cv2.cvtColor(frame, cv2.COLOR_GRAY2BGR)
            writer.write(frame)
        writer.release()


def process_trial(src_trial, dst_trial, quality):
    """Copy all files from src trial folder; convert video .ma to MJPG."""
    os.makedirs(dst_trial, exist_ok=True)
    for item in os.listdir(src_trial):
        src_item = os.path.join(src_trial, item)
        dst_item = os.path.join(dst_trial, item)
        if os.path.isdir(src_item):
            # Camera subfolder (CameraGigEBehavior)
            os.makedirs(dst_item, exist_ok=True)
            for fname in os.listdir(src_item):
                src_f = os.path.join(src_item, fname)
                if fname == VIDEO_FILE:
                    dst_f = os.path.join(dst_item, VIDEO_OUT)
                    log(f'    converting {fname} -> {VIDEO_OUT}')
                    convert_video(src_f, dst_f, quality)
                else:
                    shutil.copy2(src_f, os.path.join(dst_item, fname))
        else:
            shutil.copy2(src_item, dst_item)


def package_animal(animal, entries, dest, quality):
    archive = os.path.join(dest, f'{animal}.tar.gz')
    if os.path.exists(archive):
        log(f'SKIP {animal} ({archive} already exists)')
        return

    staging = os.path.join(dest, '_staging', animal)
    os.makedirs(staging, exist_ok=True)
    log(f'=== {animal}: {len(entries)} trial folders ===')

    try:
        for idx, (session_folder, trial_folder) in enumerate(entries, 1):
            src_trial = os.path.join(BASE_DATA, session_folder, trial_folder)
            dst_trial = os.path.join(staging, session_folder, trial_folder)
            log(f'  [{idx}/{len(entries)}] {session_folder}/{trial_folder}')
            process_trial(src_trial, dst_trial, quality)

        log(f'  Creating {os.path.basename(archive)} ...')
        with tarfile.open(archive, 'w:gz') as tar:
            tar.add(staging, arcname=animal)
        log(f'  Done: {archive}')
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dest',    default=DEFAULT_DEST,
                        help='Output directory for tar.gz archives')
    parser.add_argument('--quality', type=int, default=85,
                        help='MJPG quality 0-100 (default 85)')
    parser.add_argument('--animal',  default=None,
                        help='Process only this animal (e.g. 220211_f38)')
    args = parser.parse_args()

    os.makedirs(args.dest, exist_ok=True)

    animals = [args.animal] if args.animal else list(MANIFEST.keys())
    for animal in animals:
        if animal not in MANIFEST:
            print(f'Unknown animal: {animal}')
            sys.exit(1)
        package_animal(animal, MANIFEST[animal], args.dest, args.quality)

    # Copy README alongside the archives (only when running full packaging)
    if not args.animal:
        readme_src = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'README_zenodo.md')
        readme_dst = os.path.join(args.dest, 'README.md')
        if os.path.exists(readme_src):
            shutil.copy2(readme_src, readme_dst)
            log(f'README copied to {readme_dst}')

    log('All done.')


if __name__ == '__main__':
    main()
